### ISSUE TITLE
kafka生产消息出现错误

### ISSUE THREAD

**Issue by poohRui** [dddzg/esbc-drunkcat-fans#25]
kafka生产者和消费者传消息时报错
```
[2018-07-04 19:51:55,114] WARN Error while fetching metadata [{TopicMetadata for topic final ->
No partition metadata for topic final due to kafka.common.LeaderNotAvailableException}] for topic [final]: class kafka.common.LeaderNotAvailableException  (kafka.producer.BrokerPartitionInfo)

```
查看日志
server.log显示
```
[2018-07-04 21:00:08,072] INFO I wrote this conflicted ephemeral node [{"version":1,"brokerid":0,"timestamp":"1530704435639"}] at /controller a while back in a different session, hence I will backoff for this node to be deleted by Zookeeper and retry (kafka.utils.ZkUtils$)

```

state-change.log显示
```
[2018-07-04 19:40:35,582] TRACE Controller 0 epoch 11 started leader election for partition [final,0] (state.change.logger)
[2018-07-04 19:40:35,585] ERROR Controller 0 epoch 11 initiated state change for partition [final,0] from OfflinePartition to OnlinePartition failed (state.change.logger)
kafka.common.NoReplicaOnlineException: No replica for partition [final,0] is alive. Live brokers are: [Set()], Assigned replicas are: [List(0)]
        at kafka.controller.OfflinePartitionLeaderSelector.selectLeader(PartitionLeaderSelector.scala:61)
        at kafka.controller.PartitionStateMachine.electLeaderForPartition(PartitionStateMachine.scala:336)
        at kafka.controller.PartitionStateMachine.kafka$controller$PartitionStateMachine$$handleStateChange(PartitionStateMachine.scala:185)
        at kafka.controller.PartitionStateMachine$$anonfun$triggerOnlinePartitionStateChange$3.apply(PartitionStateMachine.scala:99)
        at kafka.controller.PartitionStateMachine$$anonfun$triggerOnlinePartitionStateChange$3.apply(PartitionStateMachine.scala:96)
        at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:772)
        at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:98)
        at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:98)
        at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:226)
        at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:39)
        at scala.collection.mutable.HashMap.foreach(HashMap.scala:98)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:771)
        at kafka.controller.PartitionStateMachine.triggerOnlinePartitionStateChange(PartitionStateMachine.scala:96)
        at kafka.controller.PartitionStateMachine.startup(PartitionStateMachine.scala:68)
        at kafka.controller.KafkaController.onControllerFailover(KafkaController.scala:312)
        at kafka.controller.KafkaController$$anonfun$1.apply$mcV$sp(KafkaController.scala:162)
        at kafka.server.ZookeeperLeaderElector.elect(ZookeeperLeaderElector.scala:63)
        at kafka.server.ZookeeperLeaderElector$$anonfun$startup$1.apply$mcZ$sp(ZookeeperLeaderElector.scala:49)
        at kafka.server.ZookeeperLeaderElector$$anonfun$startup$1.apply(ZookeeperLeaderElector.scala:47)
        at kafka.server.ZookeeperLeaderElector$$anonfun$startup$1.apply(ZookeeperLeaderElector.scala:47)
        at kafka.utils.Utils$.inLock(Utils.scala:538)
        at kafka.server.ZookeeperLeaderElector.startup(ZookeeperLeaderElector.scala:47)
        at kafka.controller.KafkaController$$anonfun$startup$1.apply$mcV$sp(KafkaController.scala:637)
        at kafka.controller.KafkaController$$anonfun$startup$1.apply(KafkaController.scala:633)
        at kafka.controller.KafkaController$$anonfun$startup$1.apply(KafkaController.scala:633)
        at kafka.utils.Utils$.inLock(Utils.scala:538)
        at kafka.controller.KafkaController.startup(KafkaController.scala:633)
        at kafka.server.KafkaServer.startup(KafkaServer.scala:96)
        at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:34)
        at kafka.Kafka$.main(Kafka.scala:46)
        at kafka.Kafka.main(Kafka.scala)

```

controller.log显示
```
[2018-07-04 19:40:23,293] INFO [ControllerEpochListener on 0]: Initialized controller epoch to 10 and zk version 9 (kafka.controller.ControllerEpochListener)
[2018-07-04 19:40:23,316] INFO [Controller 0]: Controller starting up (kafka.controller.KafkaController)
[2018-07-04 19:40:35,431] INFO [Controller 0]: Broker 0 starting become controller state transition (kafka.controller.KafkaController)
[2018-07-04 19:40:35,448] INFO [Controller 0]: Controller 0 incremented epoch to 11 (kafka.controller.KafkaController)
[2018-07-04 19:40:35,547] INFO [Controller 0]: Partitions undergoing preferred replica election:  (kafka.controller.KafkaController)
[2018-07-04 19:40:35,547] INFO [Controller 0]: Partitions that completed preferred replica election:  (kafka.controller.KafkaController)
[2018-07-04 19:40:35,548] INFO [Controller 0]: Resuming preferred replica election for partitions:  (kafka.controller.KafkaController)
[2018-07-04 19:40:35,550] INFO [Controller 0]: Partitions being reassigned: Map() (kafka.controller.KafkaController)
[2018-07-04 19:40:35,551] INFO [Controller 0]: Partitions already reassigned: List() (kafka.controller.KafkaController)
[2018-07-04 19:40:35,551] INFO [Controller 0]: Resuming reassignment of partitions: Map() (kafka.controller.KafkaController)
[2018-07-04 19:40:35,555] INFO [Controller 0]: List of topics to be deleted:  (kafka.controller.KafkaController)
[2018-07-04 19:40:35,555] INFO [Controller 0]: List of topics ineligible for deletion: test,data,flume-data,dzg,final,test2 (kafka.controller.KafkaController)
[2018-07-04 19:40:35,563] INFO [Controller 0]: Currently active brokers in the cluster: Set() (kafka.controller.KafkaController)
[2018-07-04 19:40:35,563] INFO [Controller 0]: Currently shutting brokers in the cluster: Set() (kafka.controller.KafkaController)
[2018-07-04 19:40:35,563] INFO [Controller 0]: Current list of topics in the cluster: Set(test, data, flume-data, dzg, final, test2) (kafka.controller.KafkaController)
[2018-07-04 19:40:35,566] INFO [Replica state machine on controller 0]: Started replica state machine with initial state -> Map([Topic=dzg,Partition=0,Replica=0] -> ReplicaDeletionIneligible, [Topic=test2,Partition=0,Replica=0] -> ReplicaDeletionIneligible, [Topic=test,Partition=0,Replica=0] -> ReplicaDeletionIneligible, [Topic=final,Partition=0,Replica=0] -> ReplicaDeletionIneligible, [Topic=data,Partition=0,Replica=0] -> ReplicaDeletionIneligible, [Topic=final,Partition=2,Replica=0] -> ReplicaDeletionIneligible, [Topic=final,Partition=1,Replica=0] -> ReplicaDeletionIneligible, [Topic=flume-data,Partition=0,Replica=0] -> ReplicaDeletionIneligible, [Topic=flume-data,Partition=1,Replica=0] -> ReplicaDeletionIneligible) (kafka.controller.ReplicaStateMachine)
[2018-07-04 19:40:35,573] DEBUG [OfflinePartitionLeaderSelector]: No broker in ISR is alive for [final,1]. Pick the leader from the alive assigned replicas:  (kafka.controller.OfflinePartitionLeaderSelector)
[2018-07-04 19:40:35,578] DEBUG [OfflinePartitionLeaderSelector]: No broker in ISR is alive for [data,0]. Pick the leader from the alive assigned replicas:  (kafka.controller.OfflinePartitionLeaderSelector)
[2018-07-04 19:40:35,581] DEBUG [OfflinePartitionLeaderSelector]: No broker in ISR is alive for [final,2]. Pick the leader from the alive assigned replicas:  (kafka.controller.OfflinePartitionLeaderSelector)
[2018-07-04 19:40:35,585] DEBUG [OfflinePartitionLeaderSelector]: No broker in ISR is alive for [final,0]. Pick the leader from the alive assigned replicas:  (kafka.controller.OfflinePartitionLeaderSelector)
[2018-07-04 19:40:35,589] DEBUG [OfflinePartitionLeaderSelector]: No broker in ISR is alive for [flume-data,0]. Pick the leader from the alive assigned replicas:  (kafka.controller.OfflinePartitionLeaderSelector)
[2018-07-04 19:40:35,594] DEBUG [OfflinePartitionLeaderSelector]: No broker in ISR is alive for [test,0]. Pick the leader from the alive assigned replicas:  (kafka.controller.OfflinePartitionLeaderSelector)

```

**Comment by poohRui** [comment]
原因已找到，是配置了kafka的三台机器的server.properties中的broker.id都设成一样了，导致不能选出leader。
